build: fix pypi workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -23,6 +23,14 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: "3.x"
+
+      - name: Debug Git
+        run: |
+            git config --global --add safe.directory /github/workspace
+            git status
+            git describe --tags
+            php -r "print_r(shell_exec('git describe --tags'));" || echo "PHP not found, skipping"
+
           
       - name: Install dependencies
         run: |
